### ISSUE TITLE
dev-libs/sink-0.9.0 build fails

### ISSUE THREAD

**Issue by Albert753258** [pinetoo/pinetoo#5]
[build.log](https://github.com/pinetoo/pinetoo/files/13863316/build.log)

emerge --info
`Portage 3.0.60 (python 3.11.7-final-0, !../../var/db/repos/pinetoo/profiles/pinetoo/linux/arm64/17.0/mobile/pinephone/plasma/systemd/merged-usr, gcc-13, glibc-2.38-r8, 6.6.3-pinephone aarch64)                                                   =================================================================                System uname: Linux-6.6.3-pinephone-aarch64-with-glibc2.38                       KiB Mem:     2987280 total,    468380 free                                       KiB Swap:    4295676 total,   4293116 free                                       Timestamp of repository gentoo: Wed, 03 Jan 2024 00:45:01 +0000                  Head commit of repository gentoo: 0c5110d4d95acc545dd4a3d76a24b49eb5853eb3       Head commit of repository pinetoo: 043db638caecc02cc6e5c52752ade6b6646834a6                                                                                       sh bash 5.2_p21-r1                                                               ld GNU ld (Gentoo 2.41 p4) 2.41.0                                                distcc 3.4 aarch64-unknown-linux-gnu [enabled]                                   ccache version 4.8.3 [enabled]                                                   app-misc/pax-utils:        1.3.7::gentoo                                         app-shells/bash:           5.2_p21-r1::gentoo                                    dev-lang/perl:             5.38.2-r1::gentoo                                     dev-lang/python:           3.11.7::gentoo, 3.12.1_p1::gentoo                     dev-lang/rust-bin:         1.74.1::gentoo                                        dev-util/ccache:           4.8.3::gentoo                                         dev-util/cmake:            3.28.1::gentoo                                        dev-util/meson:            1.3.1::gentoo                                         sys-apps/baselayout:       2.14-r1::gentoo                                       sys-apps/sandbox:          2.38::gentoo                                          sys-apps/systemd:          254.8::gentoo                                         sys-devel/autoconf:        2.72-r1::gentoo                                       sys-devel/automake:        1.16.5-r1::gentoo                                     sys-devel/binutils:        2.41-r3::gentoo                                       sys-devel/binutils-config: 5.5::gentoo                                           sys-devel/gcc:             13.2.1_p20230826::gentoo                              sys-devel/gcc-config:      2.11::gentoo                                          sys-devel/libtool:         2.4.7-r1::gentoo                                      sys-devel/make:            4.4.1-r1::gentoo                                      sys-kernel/linux-headers:  6.6::gentoo (virtual/os-headers)                      sys-libs/glibc:            2.38-r8::gentoo                                       Repositories:                                                                                                                                                     gentoo                                                                               location: /var/db/repos/gentoo                                                   sync-type: rsync                                                                 sync-uri: rsync://rsync.gentoo.org/gentoo-portage                                priority: -1000                                                                  volatile: False                                                                  sync-rsync-verify-jobs: 1                                                        sync-rsync-verify-metamanifest: yes                                              sync-rsync-extra-opts:                                                           sync-rsync-verify-max-age: 3                                                                                                                                  pinetoo                                                                              location: /var/db/repos/pinetoo                                                  sync-type: git                                                                   sync-uri: https://github.com/pinetoo/pinetoo                                     masters: gentoo                                                                  volatile: False                                                                                                                                               Binary Repositories:                                                                                                                                              gentoobinhost                                                                        priority: 1                                                                      sync-uri: https://gentoo.osuosl.org/releases/arm64/binpackages/17.0/arm64                                                                                     ACCEPT_KEYWORDS="amd64 arm64 ~amd64 ~arm64"                                      ACCEPT_LICENSE="*"                                                               CBUILD="aarch64-unknown-linux-gnu"                                               CFLAGS="-O2 -march=armv8-a -mtune=cortex-a53 -pipe"                              CHOST="aarch64-unknown-linux-gnu"                                                CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"           CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d"     CXXFLAGS="-O2 -march=armv8-a -mtune=cortex-a53 -pipe"                            DISTDIR="/var/cache/distfiles"                                                   ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"  FCFLAGS="-O2 -march=armv8-a -mtune=cortex-a53 -pipe"                             FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live ccache config-protect-if-modified distcc distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox pkgdir-index-trusted preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"                       FFLAGS="-O2 -march=armv8-a -mtune=cortex-a53 -pipe"                              GENTOO_MIRRORS="http://distfiles.gentoo.org"                                     LANG="C.UTF8"                                                                    LDFLAGS="-Wl,-O1 -Wl,--as-needed"                                                LEX="flex"                                                                       MAKEOPTS="-j17"                                                                  PKGDIR="/var/cache/binpkgs"                                                      PORTAGE_CONFIGROOT="/"                                                           PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"   PORTAGE_TMPDIR="/var/tmp"                                                        SHELL="/bin/bash"                                                                USE="X a52 aac acl acpi activities alsa appstream arm64 bash-completion bluetooth branding brightness-control bzip2 cairo cdr cli crypt cups dbus declarative dialer dri drm dts dvdr emoji encode evdev exif farstream ffmpeg flac flatpak fortran gdbm gif gles2 gles2-only gstreamer gui iconv icu idn ipv6 jpeg kde kms kwallet lcms libdrm libkms libnotify libtirpc lm-sensors mad mng mobile modemmanager mp3 mp4 mpeg ncurses networkmanager nls nptl office ogg opengl openmp pam pango pcre pdf pipewire plasma png policykit ppds pulseaudio qml qt5 readline screencast sdl seccomp semantic-desktop share sound spell ssl startup-notification svg systemd test-rust tiff tkip truetype tslib udev udisks unicode upower usb vorbis vpx wayland webp widgets wireless wxwidgets x264 xattr xcb xft xml xv xvid zlib" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_anon authn_dbm authn_file authz_dbm authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir env expires ext_filter file_cache filter headers include info log_config logio mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_ARM="edsp vfp vfpv3 vfpv4 vfp-d32 aes sha1 sha2 crc32 v8" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 ntrip navcom oceanserver oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 tsip tripmate tnt ublox" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz glk hd44780 lb216 lcdm001 mtxorb text" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php8-1" POSTGRES_TARGETS="postgres15" PYTHON_SINGLE_TARGET="python3_11" PYTHON_TARGETS="python3_11" RUBY_TARGETS="ruby31" VIDEO_CARDS="lima" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipp2p iface geoip fuzzy condition tarpit sysrq proto logmark ipmark dhcpmac delude chaos account"                                                   Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, PYTHONPATH, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS`

**Comment by chusopr** [comment]
Yes, `dev-libs/sink` hasn't seen any new release in two years and doesn't build with modern versions of `dev-libs/flatbuffers` and that's why it has also been removed from `::gentoo` in commit [`601e9b1`](https://gitweb.gentoo.org/repo/gentoo.git/commit/net-libs/kdav2?id=601e9b1b4c436c61e9c3a91215274c8782fb2d11).

Making it build these last two years was painful and there is no point on keeping trying it after it seems abandoned upstream, which is unfortunate because that means that features like contacts sync will be lost.

If they resume development again (maybe after the release of Plasma 6?), I will readd it. Or maybe contacts sync can be implemented otherwise using Akonadi.

The following packages will be removed as a result:

* `dev-libs/sink` - [no releases in two years](https://invent.kde.org/pim/sink/-/tags), it doesn't build with modern versions of `dev-libs/flatbuffers`
* `kde-misc/kpeoplesink` - [archived upstream](https://invent.kde.org/pim/kpeoplesink), [never had a stable release](https://invent.kde.org/pim/kpeoplesink/-/tags)
* `mail-client/kube` - [no releases in two years](https://invent.kde.org/pim/kube/-/tags) and it just doesn't work (as per my own tests)

**Comment by chusopr** [comment]
Closing this as fixed by b4e538387d18f00608283d76b9a0fcb4045f8e13.
For whatever reason, Github didn't automatically close it.
